### ISSUE TITLE
다일리 ver.0 긴급수정

### ISSUE THREAD

**Issue by puranium235** [dailry/dailry#316]
### 🐞 버그 내용
다일리 ver.0 개선 (하경) #315 
- [x] 메인 홈페이지 화면 비율
- [x] 로그인 하면 메인페이지 로그인 -> 로그아웃
- [x] 비 로그인 시 다일리 클릭 시 빈 화면
- [x] 첫 페이지 생성 시 새로고침 해야 페이지 확인 가능

### ⚗️ 재현 방법

해상도 세로 768px에서 벗어날 시 메뉴가 짤리거나 보이지 않음

**Comment by hangooksaram** [comment]
고생하셨습니다!
